# Generated by Django 5.0.3 on 2024-03-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Duration', models.DurationField()),
                ('Like', models.IntegerField(blank=True, null=True)),
                ('Share', models.IntegerField(blank=True, null=True)),
                ('Download', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_title', models.CharField(max_length=200)),
                ('Type', models.CharField(blank=True, choices=[('Story', 'Story'), ('Business', 'Business'), ('Sports', 'Sports'), ('Education', 'Education')], max_length=100, null=True)),
            ],
        ),
    ]
