# Generated by Django 5.0.3 on 2024-03-24 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='Duration',
        ),
    ]
