# Generated by Django 5.0.3 on 2024-03-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0003_premium_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
