# Generated by Django 5.0.3 on 2024-04-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0004_episode_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField(default=0.5)),
                ('current_audio_index', models.PositiveIntegerField(blank=True, null=True)),
                ('is_playing', models.BooleanField(default=False)),
            ],
        ),
    ]
