# Generated by Django 5.0.3 on 2024-04-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0005_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Like', models.IntegerField(blank=True, null=True)),
                ('Share', models.IntegerField(blank=True, null=True)),
                ('Download', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
