# Generated by Django 5.0.3 on 2024-04-18 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0007_song'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Song',
            new_name='Audio',
        ),
    ]
