# Generated by Django 5.0.3 on 2024-04-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0008_rename_song_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='artist',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='audio',
            name='title',
            field=models.TextField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
