# Generated by Django 5.0.3 on 2024-04-19 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0009_alter_audio_artist_alter_audio_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Audio',
            new_name='Song',
        ),
    ]
