# Generated by Django 5.0.3 on 2024-04-19 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0010_rename_audio_song'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Song',
            new_name='Audio',
        ),
    ]
