# Generated by Django 5.0.3 on 2024-04-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0011_rename_song_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='Type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
