# Generated by Django 5.0.3 on 2024-04-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0012_playlist_image_alter_playlist_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='Download',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='Like',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='Share',
        ),
        migrations.AddField(
            model_name='episode',
            name='Artist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='Type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
