# Generated by Django 5.0.3 on 2024-04-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0013_remove_audio_artist_remove_episode_download_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='audio_files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
