# Generated by Django 5.0.3 on 2024-04-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0015_alter_episode_audio_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='audio_files',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
