# Generated by Django 5.0.3 on 2024-04-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0017_alter_episode_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
