# Generated by Django 5.0.4 on 2024-05-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0021_alter_episode_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
    ]
