# Generated by Django 5.0.4 on 2024-05-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0022_alter_profile_is_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images'),
        ),
    ]
