# Generated by Django 5.0.3 on 2024-05-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0023_alter_episode_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('audio', models.CharField(max_length=200)),
            ],
        ),
    ]
