# Generated by Django 5.0.3 on 2024-05-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0024_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='lists',
            field=models.ManyToManyField(to='Podcast.episode'),
        ),
    ]
