# Generated by Django 5.0.3 on 2025-03-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0025_playlist_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
