# Generated by Django 5.0.3 on 2025-03-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0026_profile_expiry_date_profile_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
