# Generated by Django 5.0.3 on 2025-03-12 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0027_episode_is_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_creator',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
