# Generated by Django 5.0.3 on 2025-03-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0028_remove_profile_is_creator_remove_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
    ]
