# Generated by Django 5.0.3 on 2025-04-19 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0030_remove_playlist_type_remove_playlist_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='Podcast.playlist'),
        ),
    ]
