# Generated by Django 5.0.3 on 2025-04-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0032_playlist_artist_playlist_type_playlist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='index',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
