# Generated by Django 5.0.3 on 2025-04-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0033_audio_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='category',
            field=models.CharField(choices=[('Story', 'Story'), ('Sports', 'Sports'), ('Education', 'Education'), ('Business', 'Business'), ('Live', 'Live')], default='Story', max_length=50),
            preserve_default=False,
        ),
    ]
