# Generated by Django 5.0.3 on 2025-04-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0034_episode_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='category',
            field=models.CharField(choices=[('Story', 'Story'), ('Sports', 'Sports'), ('Education', 'Education'), ('Business', 'Business'), ('Politics', 'Politics'), ('Live', 'Live')], max_length=50),
        ),
    ]
