# Generated by Django 5.0.3 on 2025-04-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0035_alter_episode_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='category',
            field=models.CharField(choices=[('Story', 'Story'), ('Sports', 'Sports'), ('Education', 'Education'), ('Business', 'Business'), ('Politics', 'Politics'), ('Live', 'Live')], default='story', max_length=50),
            preserve_default=False,
        ),
    ]
