# Generated by Django 5.0.3 on 2025-04-22 05:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0037_alter_playlist_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
