# Generated by Django 5.0.3 on 2025-04-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Podcast', '0038_episode_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='plays',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
